### ISSUE TITLE
Well, that doesn't look good

### ISSUE THREAD

**Issue by nicolas377** [GeoFS-Autoland/fmc-requirejs#4]
![image](https://user-images.githubusercontent.com/68359871/129492412-a609b4e8-e881-4844-be32-d33ffdbdfa81.png)
![image](https://user-images.githubusercontent.com/68359871/129492415-b098d724-11c5-4953-8567-fca1ec8109f7.png)
![image](https://user-images.githubusercontent.com/68359871/129492420-fde4e968-d810-477d-8362-7d02e6e6b6df.png)

**Comment by nicolas377** [comment]
![image](https://user-images.githubusercontent.com/68359871/129492433-7f84708e-8b08-4ef4-9db4-693671e92948.png)

**Comment by nicolas377** [comment]
That's the code that triggers the error.

**Comment by Guy-Adler** [comment]
I'll look into it

**Comment by Guy-Adler** [comment]
Might be something about the minification process and prettify. not sure tho
